### ISSUE TITLE
Incluir opção para exportar/importar/compartilhar experimento:

### ISSUE THREAD

**Issue by leandro-jesus-eng** [leandro-jesus-eng/Apis-mobile-UEMS#5]
- Um experimento pode ser compartilhado por mais de um dispositivo móvel. Assim, após criar e configurar um experimento em um dispositivo deverá ser possível "exportar/compartilhar" esse experimento para que outros dispositivos possam importá-lo.
- produzir um wireframing para validação com o usuário

**Comment by FernandoAyach** [comment]
O que seria o experimento? Não localizei onde é isso no app

**Comment by FernandoAyach** [comment]
Alteração requisitada:
https://www.figma.com/file/4Dtvw6dieHw7DH9Dlq17iW/Design-Lista-de-animais-a-serem-observados?node-id=0%3A1

**Comment by leandro-jesus-eng** [comment]
Olá Fernando ... Ficou ótimo o seu design, fiz apenas um observação lá no figma. Faça essa alteração por favor.
