### ISSUE TITLE
Alterações do layout de anotação dos comportamentos:

### ISSUE THREAD

**Issue by leandro-jesus-eng** [leandro-jesus-eng/Apis-mobile-UEMS#7]
- na tela de anotação do comportamento de um animal, separar em duas abas (tabs) os comportamentos fisiológicos dos comportamentos Reprodutivos.
- Na aba comportamento reprodutivo criar uma interface para indicar que uma data VacaA montou em uma VacaB. A interface deve ser de fácil utilização e permitir q a anotação seja a mais ágil possível. Algumas vezes será anotado que um VacaA montou em uma vaca desconhecido, ou foi montada por uma vaca desconhecida.
- produzir um wireframing para validação da alteração com o usuário

**Comment by FernandoAyach** [comment]
Alteração receitada:
https://www.figma.com/file/4Dtvw6dieHw7DH9Dlq17iW/Altera%C3%A7%C3%B5es-do-aplicativo-%C3%81pis?node-id=0%3A1

**Comment by leandro-jesus-eng** [comment]
Olá Fernando. Ficou muito bom e datalhado. Encaminhei para a professora Fabiana avaliar essas alterações junto com o Odair.
